#!/bin/bash

title=$(playerctl metadata title 2>/dev/null|| echo "")
artist=$(playerctl metadata artist 2>/dev/null || echo "")
playPauze=$(playerctl status 2>/dev/null || echo "")

retVal=""

if [ "$artist" ]
then
	retVal+="${artist}: "
fi

if [ "$title" ]
then
	retVal+="${title}"
fi 

if [ "$(echo $playPauze | grep Play)" ]
then
	retVal+=" ▶"
fi

if [ "$(echo $playPauze | grep Pause)" ]
then
	retVal+=" ⏸"
fi

if [ "$retVal" ]
then
	echo $retVal
else
	echo "No playerctl playing"
fi
exit

