#!/bin/bash

#img="/tmp/lock-screen.png"
#
#escrotum "$img"
#convert "$img" -blur 0x5 "$img"
#i3lock -bt -i "$img"


#i3lock-fancy  -t "$(curl http://www.whatthecommit.com/index.txt)"
export BLOCK_BUTTON=4
/home/jan-pieter/.config/i3/i3scripts/system_keyboard_state.sh

i3lock-fancy
