#!/bin/bash
sleepTime=${1:0}
grub_location=/home/jan-pieter/custum_scripts/lockscreen/grub.png
background_location=/home/jan-pieter/custum_scripts/lockscreen/background.png

echo $(date) >> /home/jan-pieter/test
sleep $(($sleepTime))

rm $grub_location
ln -s $(random_lockscreen) $grub_location &

rm $background_location
ln -s $(random_lockscreen) $background_location &

echo $(date) >> /home/jan-pieter/test
echo $grub_location >> /home/jan-pieter/test
echo $background_location >> /home/jan-pieter/test
