#!/bin/bash
#get a random lockscreen image

image_path=${1:-/fast_files/git_repos/custum_scripts/lockscreen/background_19.png}

echo $image_path

#lock the computer

#i3lock with time and date version (i3lock-color
#i3lock -i $image_path -efk --timecolor=FFFFFFFF --datecolor=FFFFFFFF -c 000000
i3lock -i $image_path -u
