#!/bin/bash
#get a random lockscreen image

#image_path=${1:-$(random_lockscreen)}

image_path=/home/jan-pieter/custum_scripts/lockscreen/background_10.png

echo $image_path

#lock the computer

#i3lock with time and date version (i3lock-color
#i3lock -i $image_path -efk --timecolor=FFFFFFFF --datecolor=FFFFFFFF -c 000000
i3lock -i $image_path
