#!/usr/bin/bash

# Path to lock file
lock="/tmp/keyboard.lock"

# Lock the file (other atomic alternatives would be "ln" or "mkdir")
exec 9>"$lock"
if ! flock -n 9; then
        notify-send -t 5000 "Keyboard script is already running."
        exit 1
fi

notify-send "Testing stuff"
# sh /fast_files/git_repos/custum_scripts/keyboard_change

# The lock file will be unlocked when the script ends
echo '' > /tmp/keyboard.lock &
