#!/bin/bash
#get a random lockscreen image

image_path=${1:-"$HOME/Pictures/lockscreen/home_screen.png"}

echo $image_path

# update the lockscreen path
#betterlockscreen -u $image_path

#lock the computer

#i3lock with time and date version (i3lock-color
#i3lock -i $image_path

if [ $(echo $XDG_SESSION_TYPE) == "wayland" ];
then
    swaylock --image $image_path --clock --indicator
else
    betterlockscreen -l
fi
