#!/bin/sh

ID=`xinput list | egrep -io "AT Translated.*\s*id\=[0-9]{1,2}" | egrep -o '\=[0-9]{1,2}' | egrep -o '[0-9]{1,2}'`
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`

if [ $STATE -eq 1 ]
then
    xinput disable $ID
    # echo "Touchpad disabled."
    notify-send -a 'System Keyboard' 'Disabled'
else
    xinput enable $ID
    # echo "System Keyboard enabled."
    notify-send -a 'System Keyboard' 'Enabled'
fi

