#!/bin/bash
# Give the date
counter_location="$HOME/date_script_counter"
date +"%d/%m/%Y" | tr -d '\n'

# increase the counter
touch $counter_location
current="$(cat $counter_location)"

# A non-number string + 1 will give 1
new_value=$(($current + 1))
echo $new_value > $counter_location
